name: Issue Auto Fixer

on:
  issues:
    types: [labeled]

jobs:
  auto-fix:
    if: github.event.label.name == 'auto-fix'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v4

      - name: Create branch
        run: |
          branch_name="fix/issue-${{ github.event.issue.number }}"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b $branch_name

      - name: Create file with issue content
        run: |
          mkdir -p .issues
          echo "Issue Title: ${{ github.event.issue.title }}" > .issues/issue-${{ github.event.issue.number }}.txt
          echo "" >> .issues/issue-${{ github.event.issue.number }}.txt
          echo "Issue Body:" >> .issues/issue-${{ github.event.issue.number }}.txt
          echo "${{ github.event.issue.body }}" >> .issues/issue-${{ github.event.issue.number }}.txt

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Auto-fix for issue #${{ github.event.issue.number }}"
          git push origin fix/issue-${{ github.event.issue.number }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Auto-fix for issue #${{ github.event.issue.number }}"
          body: |
            This PR was automatically created in response to issue #${{ github.event.issue.number }}

            Issue Title: ${{ github.event.issue.title }}
          branch: fix/issue-${{ github.event.issue.number }}
          base: main
          labels: |
            automated
            auto-fix

      - name: Add comment to issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            I've created a pull request with the requested changes: #${{ steps.create-pull-request.outputs.pull-request-number }}

            The issue content has been saved to a file and is ready for review.
